version: "3.8"
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
    command: --admin-password '$$2y$$05$$GjehVn/GD6lW.HjUcCVF4uT9a02r1oSkE8qzxKLzxeVocb9oQ5142'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints: [node.role == manager ]

  couchdb:
    image: "couchdb:3.0.1"
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - type: bind
        source: /data/opt/couchdb/data
        target: /opt/couchdb/data
      - type: bind 
        source: /data/opt/couchdb/etc/local.d
        target: /opt/couchdb/etc/local.d
    environment:
      NODENAME: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
      COUCHDB_SECRET: "92de07df7e7a3fe14808cef90a7cc0d91"
      ERL_FLAGS: "-setcookie a20b37d83ef18efce400b3ace400036e"
    entrypoint: /bin/bash -c "cp -f /couchdb_conf /opt/couchdb/etc/local.d/docker.ini && cat /opt/couchdb/etc/local.d/docker.ini && /docker-entrypoint.sh /opt/couchdb/bin/couchdb"
    configs:
      - couchdb_conf
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints: [node.labels.couchdb == true ]

  app:
    image: "yangzy3/twitterlance"
    ports:
      - "81:80"
    deploy:
      mode: replicated
      replicas: 1

  spark:
    image: docker.io/bitnami/spark:3.1.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.spark_master == true ]

  spark_worker:
    image: docker.io/bitnami/spark:3.1.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints: [node.labels.spark_master == false ]

configs:
  couchdb_conf:
    file: ./couchdb.ini
  