---
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_swarm_module.html
- set_fact:
    join_tokens: '{{ hostvars[item]["swarm_manager_info"]["swarm_facts"]["JoinTokens"] }}'
  when: hostvars[item]["openstack"]["name"] == 'instance1'
  with_items: '{{ hostvars }}'
- debug:
    msg: "{{ join_tokens }}"

- set_fact:
    swarm_lead_ip: '{{ hostvars[item]["swarm_lead_ip"] }}'
  when: hostvars[item]["openstack"]["name"] == 'instance1'
  with_items: '{{ hostvars }}'
- debug:
    msg: "{{ swarm_lead_ip }}"

- name: Add manager nodes
  community.docker.docker_swarm:
    state: join
    join_token: '{{ join_tokens["Manager"] }}'
    remote_addrs: ['{{ swarm_lead_ip + ":2377"  }}']
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance2'
  register: swarm_node_info
- debug:
    msg: "{{ swarm_node_info }}"

- name: Add worker nodes
  community.docker.docker_swarm:
    state: join
    join_token: '{{ join_tokens["Worker"] }}'
    remote_addrs: ['{{ swarm_lead_ip + ":2377"  }}']
  when: hostvars[inventory_hostname]["openstack"]["name"] not in ['instance1', 'instance2']
  register: swarm_node_info
- debug:
    msg: "{{ swarm_node_info }}"

- name: Get info on Docker Swarm and list of registered nodes
  community.docker.docker_swarm_info:
    nodes: yes
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'
  register: result
- debug:
    msg: "{{ result }}"

- name: Add labels to 3 instances for couchdb
  community.docker.docker_node:
    hostname: '{{ item }}'
    labels:
      couchdb: 'true'
  with_items: ['instance1', 'instance2', 'instance3']
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'
  register: result
- debug:
    msg: "{{ result }}"