version: "3.7"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1

  couchdb:
    image: "couchdb:3.0.1"
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - type: bind
        source: /data
        target: /opt/couchdb/data
      - type: bind 
        source: /etc/vm.args
        target: /etc/vm.args
    environment:
      NODENAME: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
      COUCHDB_USER: "user"
      COUCHDB_PASSWORD: "pass"
      COUCHDB_SECRET: "92de07df7e7a3fe14808cef90a7cc0d91"
      ERL_FLAGS: "-setcookie a20b37d83ef18efce400b3ace400036e"
    entrypoint: /bin/bash -c "cp -f /couchdb_conf /opt/couchdb/etc/local.d/couch.ini && cat /opt/couchdb/etc/local.d/couch.ini && /docker-entrypoint.sh /opt/couchdb/bin/couchdb"
    configs:
      - couchdb_conf
    deploy:
      mode: replicated
      replicas: 1

  app:
    image: "yangzy3/twitterlance"
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1

configs:
  couchdb_conf:
    file: ./couchdb.ini
  