version: "3.8"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == manager'
    networks: 
      - backend

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks: 
      - backend

  couchdb:
    image: "ibmcom/couchdb3:3.0.0"
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /var/lib/couchdb/data/:/opt/couchdb/data
    environment:
      - NODENAME={{.Task.Name}}.{{.Task.ID}}
      - ERL_FLAGS="-setcookie a192aeb9904e6590849337933b000c99"
    configs:
      - source: couchdb_conf
        target: /opt/couchdb/etc/local.d/config.ini
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 3
        
  app:
    image: "yangzy3/twitterlance"
    ports:
      - "80:80"
    environment:
        - NODENAME={{.Task.Name}}.{{.Task.ID}}
    command: python /code/manage.py initcouchdb
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
        
networks:
  backend:
    driver: overlay

configs:
  couchdb_conf:
    file: ./couchdb.ini