---
- name: Create data directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /home/ubuntu/twitterlance/
    state: directory
    owner: ubuntu
    group: docker
    mode: '0774'

- name: Copy docker compose file
  become: yes
  ansible.builtin.copy:
    src: ../../../docker-compose.yml
    dest: /home/ubuntu/twitterlance/
    owner: ubuntu
    group: docker
    mode: '0774'

- name: Copy shared couchdb configuration
  become: yes
  ansible.builtin.copy:
    src: ../../../couchdb.ini
    dest: /home/ubuntu/twitterlance/
    owner: ubuntu
    group: docker
    mode: '0774'

- name: Copy couchdb cluster tools
  become: yes
  ansible.builtin.copy:
    src: ../../../couchdb_cluster/
    dest: /home/ubuntu/twitterlance/
    directory_mode: yes
    owner: ubuntu
    group: docker
    mode: '0774'

- name: print files
  command: ls /home/ubuntu/twitterlance/
  register: result
- debug:
    msg: '{{ result.stdout }}'

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: twitterlance
    compose:
      - /home/ubuntu/twitterlance/docker-compose.yml
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'
  register: result
- debug:
    msg: "{{ result }}"

- name: Wait for port 5984 of any IP to close active connections, don't start checking for 10 seconds
  wait_for:
    host: 127.0.0.1
    port: 5984
    delay: 10
    state: present

- name: Set up Couchdb cluster
  command: python3 /home/ubuntu/twitterlance/recluster.py
  register: result
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'  
  args:
    warn: no
- debug:
    msg: '{{ result }}'

# uri module has an issue with couchdb authentication 
- name: Init couchdb default database
  shell: curl -X PUT http://user:pass@127.0.0.1:5984/_users
  register: result
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'
  args:
    warn: no  
- debug:
    msg: '{{ result}}' 

- name: Init couchdb default database
  shell: curl -X PUT http://user:pass@127.0.0.1:5984/_replicator
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'  
  register: result
  args:
    warn: no
- debug:
    msg: '{{ result}}' 

- name: Init couchdb default database
  shell: curl -X PUT http://user:pass@127.0.0.1:5984/_global_changes
  when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'  
  register: result
  args:
    warn: no
- debug:
    msg: '{{ result}}' 