---
- name: Playbook
  hosts: localhost
  tasks:
  - set_fact:
      ip: '{{ hostvars[item]["ansible_host"] + ":2377" }}'
    when: hostvars[item]["openstack"]["name"] == 'instance1'
    with_items: '{{ hostvars }}'
  - debug:
        msg: "{{ ip }}"
