- hosts: all
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: environment
    - role: swarm-init
    - role: swarm-nodes
    - role: applications
      when: hostvars[inventory_hostname]["openstack"]["name"] == 'instance1'  


