- hosts: localhost
  vars: 
    ansible_python_interpreter: python3
  vars_files:
    - host_vars_scale.yaml
  gather_facts: true
  roles:
    - role: openstack-common
    - role: add-openstack-volume
    - role: openstack-security-group
    - role: add-openstack-instance


