- hosts: all
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars_scale.yaml
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: find-swarm-join-token
    - role: environment
      when: hostvars[inventory_hostname]["openstack"]["name"] in instances
    - role: add-swarm-workers